export type ShipmentResponse={
    shipmentId:string;
    name:string;
    description:string;
    status:string;
    orderId:string;
    token:string;
    redirectUrl:string;
    quantity:number;
    height:number;
    width:number;
    length:number;
    weight:number;
    category:string;
    courierCompany:string;
    courierType:string;
    orderNote:string|null;
    originNote:string|null;
    destinationNote:string|null;
}